# -*- coding: utf-8 -*-
"""Analisa Harga Jual Mercedes-Benz C Class UK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u4UAbMnUZRdKv7K5PRlZsDrqjmrmYJzd

Import Library
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

"""##Informasi Dataset"""

df = pd.read_csv('cclass.csv')

print(df.head(5))

print(df.describe)

print(df.dtypes)

print(df.isnull().sum())

"""Terdapat 5 null dalam kolom 'year' dan 7 null dalam kolom 'mileage'

##Mengisi nilai null

Mengisi nilai null dengan nilai rata rata kolom
"""

df['year'].fillna(df['year'].mean(), inplace=True)
df['mileage'].fillna(df['mileage'].mean(), inplace=True)

"""men-cek kembali jumlah null dalam tiap kolom"""

print(df.isnull().sum())

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

print("Kolom numerik di dataset:")
print(list(numeric_cols))

"""##Memeriksa Outliers Kolom "year"
"""

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['year'])
plt.title('Boxplot Tahun Unit')
plt.show()

"""Terdapat outliers yang sangat jauh dari distribusi data kolom 'year'

Menghapus outliers diluar 2012 sehingga outliers yang jauh dari kelompok distribusi data terhapus.
"""

df = df[df['year'] >= 2012]

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['year'])
plt.title('Boxplot Tahun Unit')
plt.show()

"""##Memeriksa outliers kolom "mileage"
"""

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['mileage'])
plt.title('Boxplot Jarak Tempuh Unit')
plt.show()

mileage_median = cleaned_df['mileage'].median()
cleaned_df.loc[cleaned_df['mileage'] > 75000, 'mileage'] = mileage_median

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['mileage'])
plt.title('Boxplot Jarak Tempuh Unit')
plt.show()

"""Data kolom 'mileage' yang berisikan jarak tempuh(KM) sangat variatif. saya memilih untuk tidak menghapus outlier untuk menghindari bias

##Memeriksa outlier "price"
"""

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['price'])
plt.title('Boxplot Harga Unit')
plt.show()

"""Data kolom 'price' yang berisikan harga(GBP) sangat variatif. saya memilih untuk tidak menghapus outlier untuk menghindari bias

##Memeriksa Outliers kolom "engineSize"
"""

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['engineSize'])
plt.title('Boxplot Ukuran Mesin Unit')
plt.show()

df.loc[df['mileage'] < 100, 'mileage'] = df['mileage'].median()

sns.set(style="whitegrid")
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='year', y='price', hue='model')
plt.title('Persebaran Harga Unit Berdasarkan Tahun Jual Unit')
plt.xlabel('Tahun Penjualan')
plt.ylabel('Harga Unit (GBP)')
plt.show()

"""Hasil analisa antara Harga Unit (GBP) dan Tahun Penjualan menampilkan bahwa distribusi dan penyebaran data harga unit Mercedes-Benz C Class UK dengan tahun jual lama rata rata memiliki nilai jual yang lebih rendah, sebaliknya bahwa distribusi dan penyebaran data harga mobil dengan tahun terknini masih memiliki nilai jual yang lebih tinggi."""

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='engineSize', y='price')
plt.title('Distribusi Harga Berdasarkan Ukuran Mesin')
plt.xlabel('Ukuran Mesin (L)')
plt.ylabel('Harga Mobil (GBP)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Hasil analisa antara Harga Unit dan Ukuran Mesin menampilkan bahwa distribusi dan penyebaran data ukuran Mesin unit Mercedes-Benz C Class UK tersebar secara variatif. Terdapat sejumlah ukuran mesin kecil dengan harga yang lebih tinggi dari sejumlah nilai jual ukuran mesin yang lebih besar."""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='mileage', y='price', hue='model', alpha=0.7)
plt.title('Persebaran Harga Unit Berdasarkan Jarak Tempuh Unit')
plt.xlabel('Mileage (km)')
plt.ylabel('Harga Mobil (GBP)')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Hasil analisa antara Harga Unit (GBP) dan Jarak Tempuh Unit (KM) menampilkan bahwa harga jual Mercedes-Benz C Class UK yang memiliki jarak tempuh (KM) rendah memiliki harga jual unit yang lebih tinggi dibanding sebaliknya."""